# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Oct 10 22:49:04 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pythonEdit = QPythonEdit(self.splitter)
        self.pythonEdit.setObjectName(_fromUtf8("pythonEdit"))
        self.glPreviewWidget = GLPreviewWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glPreviewWidget.sizePolicy().hasHeightForWidth())
        self.glPreviewWidget.setSizePolicy(sizePolicy)
        self.glPreviewWidget.setObjectName(_fromUtf8("glPreviewWidget"))
        self.consoleTextEdit = QtGui.QTextEdit(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleTextEdit.sizePolicy().hasHeightForWidth())
        self.consoleTextEdit.setSizePolicy(sizePolicy)
        self.consoleTextEdit.setReadOnly(True)
        self.consoleTextEdit.setObjectName(_fromUtf8("consoleTextEdit"))
        self.gridLayout.addWidget(self.splitter_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRecent_Files = QtGui.QMenu(self.menuFile)
        self.menuRecent_Files.setObjectName(_fromUtf8("menuRecent_Files"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuFind_Replace = QtGui.QMenu(self.menuEdit)
        self.menuFind_Replace.setObjectName(_fromUtf8("menuFind_Replace"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menu3D_View = QtGui.QMenu(self.menubar)
        self.menu3D_View.setObjectName(_fromUtf8("menu3D_View"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.findAndReplacedockWidget = QtGui.QDockWidget(MainWindow)
        self.findAndReplacedockWidget.setFeatures(QtGui.QDockWidget.DockWidgetClosable)
        self.findAndReplacedockWidget.setObjectName(_fromUtf8("findAndReplacedockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.findTextEdit = QtGui.QPlainTextEdit(self.dockWidgetContents)
        self.findTextEdit.setObjectName(_fromUtf8("findTextEdit"))
        self.verticalLayout.addWidget(self.findTextEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.replaceTextEdit = QtGui.QPlainTextEdit(self.dockWidgetContents)
        self.replaceTextEdit.setObjectName(_fromUtf8("replaceTextEdit"))
        self.verticalLayout_3.addWidget(self.replaceTextEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.findButton = QtGui.QPushButton(self.dockWidgetContents)
        self.findButton.setObjectName(_fromUtf8("findButton"))
        self.horizontalLayout_4.addWidget(self.findButton)
        self.replaceButton = QtGui.QPushButton(self.dockWidgetContents)
        self.replaceButton.setObjectName(_fromUtf8("replaceButton"))
        self.horizontalLayout_4.addWidget(self.replaceButton)
        self.replaceAllButton = QtGui.QPushButton(self.dockWidgetContents)
        self.replaceAllButton.setObjectName(_fromUtf8("replaceAllButton"))
        self.horizontalLayout_4.addWidget(self.replaceAllButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.findCaseSensitiveCheckBox = QtGui.QCheckBox(self.dockWidgetContents)
        self.findCaseSensitiveCheckBox.setObjectName(_fromUtf8("findCaseSensitiveCheckBox"))
        self.horizontalLayout_5.addWidget(self.findCaseSensitiveCheckBox)
        self.findRegexCheckBox = QtGui.QCheckBox(self.dockWidgetContents)
        self.findRegexCheckBox.setObjectName(_fromUtf8("findRegexCheckBox"))
        self.horizontalLayout_5.addWidget(self.findRegexCheckBox)
        self.findWholeWordCheckBox = QtGui.QCheckBox(self.dockWidgetContents)
        self.findWholeWordCheckBox.setObjectName(_fromUtf8("findWholeWordCheckBox"))
        self.horizontalLayout_5.addWidget(self.findWholeWordCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.findAndReplacedockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.findAndReplacedockWidget)
        self.actionNew_File = QtGui.QAction(MainWindow)
        self.actionNew_File.setObjectName(_fromUtf8("actionNew_File"))
        self.actionOpen_File = QtGui.QAction(MainWindow)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.actionSave_all = QtGui.QAction(MainWindow)
        self.actionSave_all.setObjectName(_fromUtf8("actionSave_all"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionClose_All = QtGui.QAction(MainWindow)
        self.actionClose_All.setObjectName(_fromUtf8("actionClose_All"))
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionFull_Screen = QtGui.QAction(MainWindow)
        self.actionFull_Screen.setObjectName(_fromUtf8("actionFull_Screen"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionClear_All = QtGui.QAction(MainWindow)
        self.actionClear_All.setObjectName(_fromUtf8("actionClear_All"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionFind_Replace = QtGui.QAction(MainWindow)
        self.actionFind_Replace.setObjectName(_fromUtf8("actionFind_Replace"))
        self.actionFind_Next = QtGui.QAction(MainWindow)
        self.actionFind_Next.setObjectName(_fromUtf8("actionFind_Next"))
        self.actionFind_Previous = QtGui.QAction(MainWindow)
        self.actionFind_Previous.setObjectName(_fromUtf8("actionFind_Previous"))
        self.actionReplace = QtGui.QAction(MainWindow)
        self.actionReplace.setObjectName(_fromUtf8("actionReplace"))
        self.actionReplace_Find = QtGui.QAction(MainWindow)
        self.actionReplace_Find.setObjectName(_fromUtf8("actionReplace_Find"))
        self.actionReplace_All = QtGui.QAction(MainWindow)
        self.actionReplace_All.setObjectName(_fromUtf8("actionReplace_All"))
        self.actionForce_Update = QtGui.QAction(MainWindow)
        self.actionForce_Update.setObjectName(_fromUtf8("actionForce_Update"))
        self.actionRun_From_Start = QtGui.QAction(MainWindow)
        self.actionRun_From_Start.setObjectName(_fromUtf8("actionRun_From_Start"))
        self.actionRun_From_Last_Statement = QtGui.QAction(MainWindow)
        self.actionRun_From_Last_Statement.setObjectName(_fromUtf8("actionRun_From_Last_Statement"))
        self.actionPerspective = QtGui.QAction(MainWindow)
        self.actionPerspective.setCheckable(False)
        self.actionPerspective.setObjectName(_fromUtf8("actionPerspective"))
        self.actionReset_Camera = QtGui.QAction(MainWindow)
        self.actionReset_Camera.setObjectName(_fromUtf8("actionReset_Camera"))
        self.menuRecent_Files.addSeparator()
        self.menuRecent_Files.addAction(self.actionClear_All)
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.menuRecent_Files.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFind_Replace.addAction(self.actionFind_Replace)
        self.menuFind_Replace.addSeparator()
        self.menuFind_Replace.addAction(self.actionFind_Next)
        self.menuFind_Replace.addAction(self.actionFind_Previous)
        self.menuFind_Replace.addAction(self.actionReplace)
        self.menuFind_Replace.addAction(self.actionReplace_All)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuFind_Replace.menuAction())
        self.menuWindow.addAction(self.actionFull_Screen)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menuRun.addAction(self.actionRun_From_Start)
        self.menuRun.addAction(self.actionRun_From_Last_Statement)
        self.menu3D_View.addAction(self.actionPerspective)
        self.menu3D_View.addAction(self.actionReset_Camera)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menu3D_View.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuRecent_Files.setTitle(_translate("MainWindow", "Recent Files", None))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menuFind_Replace.setTitle(_translate("MainWindow", "&Find/Replace", None))
        self.menuWindow.setTitle(_translate("MainWindow", "&Window", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.menuRun.setTitle(_translate("MainWindow", "&Run", None))
        self.menu3D_View.setTitle(_translate("MainWindow", "3D View", None))
        self.findAndReplacedockWidget.setWindowTitle(_translate("MainWindow", "Find And Replace", None))
        self.label.setText(_translate("MainWindow", "Find", None))
        self.label_2.setText(_translate("MainWindow", "Replace", None))
        self.findButton.setText(_translate("MainWindow", "&Find", None))
        self.replaceButton.setText(_translate("MainWindow", "&Replace", None))
        self.replaceAllButton.setText(_translate("MainWindow", "Replace &All", None))
        self.findCaseSensitiveCheckBox.setText(_translate("MainWindow", "Case Sensitive", None))
        self.findRegexCheckBox.setText(_translate("MainWindow", "Regex", None))
        self.findWholeWordCheckBox.setText(_translate("MainWindow", "Whole word", None))
        self.actionNew_File.setText(_translate("MainWindow", "&New File", None))
        self.actionNew_File.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOpen_File.setText(_translate("MainWindow", "&Open File", None))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave_all.setText(_translate("MainWindow", "Save a&ll", None))
        self.actionSave_all.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionClose.setText(_translate("MainWindow", "&Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.actionClose_All.setText(_translate("MainWindow", "Close All", None))
        self.actionClose_All.setShortcut(_translate("MainWindow", "Ctrl+Shift+W", None))
        self.actionPrint.setText(_translate("MainWindow", "&Print", None))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionExit.setText(_translate("MainWindow", "E&xit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionUndo.setText(_translate("MainWindow", "&Undo ", None))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionRedo.setText(_translate("MainWindow", "&Redo", None))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z", None))
        self.actionCut.setText(_translate("MainWindow", "Cu&t", None))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.actionCopy.setText(_translate("MainWindow", "&Copy", None))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.actionPaste.setText(_translate("MainWindow", "&Paste", None))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.actionDelete.setText(_translate("MainWindow", "&Delete", None))
        self.actionSelect_All.setText(_translate("MainWindow", "Select &All", None))
        self.actionSelect_All.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.actionFull_Screen.setText(_translate("MainWindow", "Full Screen", None))
        self.actionFull_Screen.setShortcut(_translate("MainWindow", "Ctrl+Shift+F11", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionClear_All.setText(_translate("MainWindow", "Clear All", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))
        self.actionFind_Replace.setText(_translate("MainWindow", "Find/Replace", None))
        self.actionFind_Replace.setShortcut(_translate("MainWindow", "Ctrl+F", None))
        self.actionFind_Next.setText(_translate("MainWindow", "Find Next", None))
        self.actionFind_Next.setShortcut(_translate("MainWindow", "F3", None))
        self.actionFind_Previous.setText(_translate("MainWindow", "Find Previous", None))
        self.actionFind_Previous.setShortcut(_translate("MainWindow", "Shift+F3", None))
        self.actionReplace.setText(_translate("MainWindow", "Replace", None))
        self.actionReplace_Find.setText(_translate("MainWindow", "Replace && Find", None))
        self.actionReplace_All.setText(_translate("MainWindow", "Replace All", None))
        self.actionForce_Update.setText(_translate("MainWindow", "Force Update", None))
        self.actionRun_From_Start.setText(_translate("MainWindow", "Run From &Start", None))
        self.actionRun_From_Start.setIconText(_translate("MainWindow", "Run From Start", None))
        self.actionRun_From_Start.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionRun_From_Last_Statement.setText(_translate("MainWindow", "Run From &Last Statement", None))
        self.actionRun_From_Last_Statement.setShortcut(_translate("MainWindow", "Ctrl+Shift+R", None))
        self.actionPerspective.setText(_translate("MainWindow", "Ortho/Perspective", None))
        self.actionReset_Camera.setText(_translate("MainWindow", "Reset Camera", None))

from qpython_edit import QPythonEdit
from gl_preview_widget import GLPreviewWidget
